spring:
  messages:
    baseName: messages
    encoding: UTF-8
    fallbackToSystemLocale: true
test:
  rightAnswersCountToPass: 3
  locale: ru_RU
  fileNameByLocaleTag:
    ru-RU: questions_ru.csv
    en-US: questions.csv
  locale-bundle-path: classpath:i18n\messages