server:
  port: 8081

spring:
  application:
    name: client-service
  profiles:
    active: resilience4j
  cloud:
    config:
      enabled: false
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: beans,health,info,metrics,prometheus,threaddump,heapdump,loggers,env,env-details,env-health
  endpoint:
    health:
  health:
    defaults:
      enabled: true

#https://habr.com/ru/articles/544074/
#https://www.baeldung.com/spring-boot-resilience4j
resilience4j:
  circuitbreaker:
    instances:
      circuitBreakerService:
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 5
        sliding-window-type: count_based
        slow-call-duration-threshold: 10s
