spring:
  data:
    mongodb:
      authentication-database: admin
      username: rellai
      password: "131353"
      database: book_db
      port: 27017
      host: localhost
mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package: ru.otus.aivanov.home08.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
